Revert "temporarily turn off dirty release checking."
This reverts commit e3f7686305b3ccaac71c0dcbc92d126a2b73d516.

Also retries the string prefix dirtiness detection.  Turns out we needed
a few small touch-ups.

Change-Id: I1345eb8f2da6a260cdb4822a8f371b7fa51c9745

diff --git a/Makefile.release b/Makefile.release
--- a/Makefile.release
+++ b/Makefile.release
@@ -45,8 +45,17 @@ include Makefile
 
 ##### TARGETS #####
 
+# Checks the version tag to see if its dirty.  We should never release from
+# a dirty git client.
+check-dirty:
+	@echo "VERSION=$(VERSION)"
+	@if [[ $(VERSION) == *"dirty"* ]]; then \
+		echo "Cannot release from a dirty client: VERSION=$(VERSION)"; \
+		exit 1; \
+    fi
+
 # Releases the run-installer script to GCS bucket.
-release: clean installer-image
+release: clean check-dirty installer-image
 	@gsutil cp $(TOP_DIR)/scripts/run-installer.sh $(RELEASE_BUCKET)
 	gsutil acl ch -r -u AllUsers:R $(RELEASE_BUCKET)/run-installer.sh
 
