Add invalid .yaml error example
Create parse-errors/invalid-yaml.
Make parsing errors encountered in individual files more readable.
Move expected-errs.txt to examples/errors so the expected errors and
files are in the same dir and easily discoverable.
Fix MultiError implementation of error interface.
Add regression test to Makefile with instructions for updating expected
errors.

Bug: 73786372

Change-Id: Ie2883ac478821b5d39675c453c289920c1908f9c

diff --git a/Makefile.e2e b/Makefile.e2e
--- a/Makefile.e2e
+++ b/Makefile.e2e
@@ -103,7 +103,15 @@ test-nomosvet-local: build
 		rm $(TOP_DIR)/.output/tmp/actual-errors.txt; \
 	fi
 	$(NOMOSVET_LOCAL) $(TOP_DIR)/examples/errors 2> $(TOP_DIR)/.output/tmp/actual-errs.txt || true
-	@diff $(TOP_DIR)/test/expected-errs.txt $(TOP_DIR)/.output/tmp/actual-errs.txt
+	@diff $(TOP_DIR)/examples/errors/expected-errs.txt $(TOP_DIR)/.output/tmp/actual-errs.txt
+
+# To update expected errors: nomosvet examples/parse-errors/invalid-yaml 2> examples/parse-errors/invalid-yaml/expected-errs.txt
+	@if [ -f $(TOP_DIR)/.output/tmp/actual-errors-2.txt ]; then \
+    rm $(TOP_DIR)/.output/tmp/actual-errors-2.txt; \
+  fi
+	$(NOMOSVET_LOCAL) $(TOP_DIR)/examples/parse-errors/invalid-yaml 2> $(TOP_DIR)/.output/tmp/actual-errs.txt || true
+	@grep -qF "2 error(s)" $(TOP_DIR)/.output/tmp/actual-errs.txt # there are two errors
+	@grep -cF "invalid object to validate" .output/tmp/actual-errs.txt | grep -qF 2 # they are invalid yaml
 
 include Makefile.e2e.ci
 include Makefile.e2e.prober
