Upgrade bats to 1.1.0
We were on 0.4.0, which was some old stuff. Upgrade for great good.

Tested:
ran make tests and make test-e2e-git locally and both passed with no
issues

Bug: 123659968
Change-Id: I8112d87944e2f92da179cce5681f62425778462a

diff --git a/third_party/bats-core/libexec/bats-core/bats-exec-test b/third_party/bats-core/libexec/bats-core/bats-exec-test
--- a/third_party/bats-core/libexec/bats-core/bats-exec-test
+++ b/third_party/bats-core/libexec/bats-core/bats-exec-test
@@ -1,26 +1,24 @@
 #!/usr/bin/env bash
-set -e
-set -E
-set -T
+set -eET
 
 BATS_COUNT_ONLY=""
-if [ "$1" = "-c" ]; then
+if [[ "$1" = "-c" ]]; then
   BATS_COUNT_ONLY=1
   shift
 fi
 
 BATS_EXTENDED_SYNTAX=""
-if [ "$1" = "-x" ]; then
+if [[ "$1" = "-x" ]]; then
   BATS_EXTENDED_SYNTAX="$1"
   shift
 fi
 
 BATS_TEST_FILENAME="$1"
-if [ -z "$BATS_TEST_FILENAME" ]; then
-  echo "usage: bats-exec <filename>" >&2
+if [[ -z "$BATS_TEST_FILENAME" ]]; then
+  printf 'usage: bats-exec-test <filename>\n' >&2
   exit 1
-elif [ ! -f "$BATS_TEST_FILENAME" ]; then
-  echo "bats: $BATS_TEST_FILENAME does not exist" >&2
+elif [[ ! -f "$BATS_TEST_FILENAME" ]]; then
+  printf 'bats: %s does not exist\n' "$BATS_TEST_FILENAME" >&2
   exit 1
 else
   shift
@@ -33,14 +31,14 @@ load() {
   local name="$1"
   local filename
 
-  if [ "${name:0:1}" = "/" ]; then
+  if [[ "${name:0:1}" = "/" ]]; then
     filename="${name}"
   else
     filename="$BATS_TEST_DIRNAME/${name}.bash"
   fi
 
   if [[ ! -f "$filename" ]]; then
-    echo "bats: $filename does not exist" >&2
+    printf 'bats: %s does not exist\n' "$filename" >&2
     exit 1
   fi
 
@@ -48,42 +46,35 @@ load() {
 }
 
 run() {
-  local e E T oldIFS
-  [[ ! "$-" =~ e ]] || e=1
-  [[ ! "$-" =~ E ]] || E=1
-  [[ ! "$-" =~ T ]] || T=1
-  set +e
-  set +E
-  set +T
+  local origFlags="$-"
+  set +eET
+  local origIFS="$IFS"
   output="$("$@" 2>&1)"
   status="$?"
-  oldIFS=$IFS
   IFS=$'\n' lines=($output)
-  [ -z "$e" ] || set -e
-  [ -z "$E" ] || set -E
-  [ -z "$T" ] || set -T
-  IFS=$oldIFS
+  IFS="$origIFS"
+  set "-$origFlags"
 }
 
 setup() {
-  true
+  return 0
 }
 
 teardown() {
-  true
+  return 0
 }
 
 BATS_TEST_SKIPPED=''
 skip() {
-  BATS_TEST_SKIPPED=${1:-1}
+  BATS_TEST_SKIPPED="${1:-1}"
   BATS_TEST_COMPLETED=1
   exit 0
 }
 
 bats_test_begin() {
   BATS_TEST_DESCRIPTION="$1"
-  if [ -n "$BATS_EXTENDED_SYNTAX" ]; then
-    echo "begin $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
+  if [[ -n "$BATS_EXTENDED_SYNTAX" ]]; then
+    printf 'begin %d %s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" >&3
   fi
   setup
 }
@@ -98,7 +89,7 @@ BATS_PREVIOUS_STACK_TRACE=()
 BATS_ERROR_STACK_TRACE=()
 
 bats_capture_stack_trace() {
-  if [[ "${#BATS_CURRENT_STACK_TRACE[@]}" -ne '0' ]]; then
+  if [[ "${#BATS_CURRENT_STACK_TRACE[@]}" -ne 0 ]]; then
     BATS_PREVIOUS_STACK_TRACE=("${BATS_CURRENT_STACK_TRACE[@]}")
   fi
   BATS_CURRENT_STACK_TRACE=()
@@ -107,11 +98,15 @@ bats_capture_stack_trace() {
   local setup_pattern=" setup $BATS_TEST_SOURCE"
   local teardown_pattern=" teardown $BATS_TEST_SOURCE"
 
+  local source_file
   local frame
   local i
 
   for ((i=2; i != ${#FUNCNAME[@]}; ++i)); do
-    frame="${BASH_LINENO[$((i-1))]} ${FUNCNAME[$i]} ${BASH_SOURCE[$i]}"
+    # Use BATS_TEST_SOURCE if necessary to work around Bash < 4.4 bug whereby
+    # calling an exported function erases the test file's BASH_SOURCE entry.
+    source_file="${BASH_SOURCE[$i]:-$BATS_TEST_SOURCE}"
+    frame="${BASH_LINENO[$((i-1))]} ${FUNCNAME[$i]} $source_file"
     BATS_CURRENT_STACK_TRACE["${#BATS_CURRENT_STACK_TRACE[@]}"]="$frame"
     if [[ "$frame" = *"$test_pattern"     || \
           "$frame" = *"$setup_pattern"    || \
@@ -136,22 +131,22 @@ bats_print_stack_trace() {
     bats_trim_filename "$filename" 'filename'
     bats_frame_lineno "$frame" 'lineno'
 
-    if [ $index -eq 1 ]; then
-      echo -n "# ("
+    if [[ $index -eq 1 ]]; then
+      printf '# ('
     else
-      echo -n "#  "
+      printf '#  '
     fi
 
     local fn
     bats_frame_function "$frame" 'fn'
-    if [ "$fn" != "$BATS_TEST_NAME" ]; then
-      echo -n "from function \`$fn' "
+    if [[ "$fn" != "$BATS_TEST_NAME" ]]; then
+      printf "from function \`%s' " "$fn"
     fi
 
-    if [ $index -eq $count ]; then
-      echo "in test file $filename, line $lineno)"
+    if [[ $index -eq $count ]]; then
+      printf 'in test file %s, line %d)\n' "$filename" "$lineno"
     else
-      echo "in file $filename, line $lineno,"
+      printf 'in file %s, line %d,\n' "$filename" "$lineno"
     fi
 
     let index+=1
@@ -172,10 +167,10 @@ bats_print_failed_command() {
   bats_strip_string "$failed_line" 'failed_command'
   printf '%s' "#   \`${failed_command}' "
 
-  if [ $status -eq 1 ]; then
-    echo "failed"
+  if [[ $status -eq 1 ]]; then
+    printf 'failed\n'
   else
-    echo "failed with status $status"
+    printf 'failed with status %d\n' "$status"
   fi
 }
 
@@ -192,7 +187,7 @@ bats_frame_filename() {
   local __bff_filename="${1#* }"
   __bff_filename="${__bff_filename#* }"
 
-  if [ "$__bff_filename" = "$BATS_TEST_SOURCE" ]; then
+  if [[ "$__bff_filename" = "$BATS_TEST_SOURCE" ]]; then
     __bff_filename="$BATS_TEST_FILENAME"
   fi
   printf -v "$2" '%s' "$__bff_filename"
@@ -200,7 +195,7 @@ bats_frame_filename() {
 
 bats_extract_line() {
   local __bats_extract_line_line
-  local __bats_extract_line_index='0'
+  local __bats_extract_line_index=0
 
   while IFS= read -r __bats_extract_line_line; do
     if [[ "$((++__bats_extract_line_index))" -eq "$2" ]]; then
@@ -216,15 +211,11 @@ bats_strip_string() {
 }
 
 bats_trim_filename() {
-  if [[ "$1" =~ ^${BATS_CWD}/ ]]; then
-    printf -v "$2" '%s' "${1#$BATS_CWD/}"
-  else
-    printf -v "$2" '%s' "$1"
-  fi
+  printf -v "$2" '%s' "${1#$BATS_CWD/}"
 }
 
 bats_debug_trap() {
-  if [ "$BASH_SOURCE" != "$1" ]; then
+  if [[ "$BASH_SOURCE" != "$1" ]]; then
     bats_capture_stack_trace
   fi
 }
@@ -244,7 +235,7 @@ bats_debug_trap() {
 bats_error_trap() {
   local status="$?"
   if [[ -z "$BATS_TEST_COMPLETED" ]]; then
-    BATS_ERROR_STATUS="$status"
+    BATS_ERROR_STATUS="${BATS_ERROR_STATUS:-$status}"
     if [[ "$BATS_ERROR_STATUS" -eq 0 ]]; then
       BATS_ERROR_STATUS=1
     fi
@@ -258,9 +249,9 @@ bats_teardown_trap() {
   local status=0
   teardown >>"$BATS_OUT" 2>&1 || status="$?"
 
-  if [ $status -eq 0 ]; then
+  if [[ $status -eq 0 ]]; then
     BATS_TEARDOWN_COMPLETED=1
-  elif [ -n "$BATS_TEST_COMPLETED" ]; then
+  elif [[ -n "$BATS_TEST_COMPLETED" ]]; then
     BATS_ERROR_STATUS="$status"
     BATS_ERROR_STACK_TRACE=( "${BATS_CURRENT_STACK_TRACE[@]}" )
   fi
@@ -269,18 +260,19 @@ bats_teardown_trap() {
 }
 
 bats_exit_trap() {
+  local line
   local status
   local skipped=''
   trap - err exit
 
-  if [ -n "$BATS_TEST_SKIPPED" ]; then
+  if [[ -n "$BATS_TEST_SKIPPED" ]]; then
     skipped=" # skip"
-    if [ "1" != "$BATS_TEST_SKIPPED" ]; then
+    if [[ "$BATS_TEST_SKIPPED" != '1' ]]; then
       skipped+=" $BATS_TEST_SKIPPED"
     fi
   fi
 
-  if [ -z "$BATS_TEST_COMPLETED" ] || [ -z "$BATS_TEARDOWN_COMPLETED" ]; then
+  if [[ -z "$BATS_TEST_COMPLETED" || -z "$BATS_TEARDOWN_COMPLETED" ]]; then
     if [[ "${#BATS_ERROR_STACK_TRACE[@]}" -eq 0 ]]; then
       # For some versions of bash, `$?` may not be set properly for some error
       # conditions before triggering the EXIT trap directly (see #72 and #81).
@@ -294,13 +286,22 @@ bats_exit_trap() {
       BATS_ERROR_STACK_TRACE=( "${BATS_PREVIOUS_STACK_TRACE[@]}" )
       BATS_ERROR_STATUS=1
     fi
-    echo "not ok $BATS_TEST_NUMBER $BATS_TEST_DESCRIPTION" >&3
+    printf 'not ok %d %s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" >&3
     bats_print_stack_trace "${BATS_ERROR_STACK_TRACE[@]}" >&3
-    bats_print_failed_command "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" "$BATS_ERROR_STATUS" >&3
-    sed -e "s/^/# /" < "$BATS_OUT" >&3
+    bats_print_failed_command \
+      "${BATS_ERROR_STACK_TRACE[${#BATS_ERROR_STACK_TRACE[@]}-1]}" \
+      "$BATS_ERROR_STATUS" >&3
+
+    while IFS= read -r line; do
+      printf '# %s\n' "$line"
+    done <"$BATS_OUT" >&3
+    if [[ -n "$line" ]]; then
+      printf '# %s\n' "$line"
+    fi
     status=1
   else
-    echo "ok ${BATS_TEST_NUMBER} ${BATS_TEST_DESCRIPTION}${skipped}" >&3
+    printf 'ok %d %s%s\n' "$BATS_TEST_NUMBER" "$BATS_TEST_DESCRIPTION" \
+      "$skipped" >&3
     status=0
   fi
 
@@ -309,11 +310,14 @@ bats_exit_trap() {
 }
 
 bats_perform_tests() {
-  echo "1..$#"
+  printf '1..%d\n' "$#"
   test_number=1
   status=0
   for test_name in "$@"; do
-    "$0" $BATS_EXTENDED_SYNTAX "$BATS_TEST_FILENAME" "$test_name" "$test_number" || status=1
+    if ! "$0" $BATS_EXTENDED_SYNTAX "$BATS_TEST_FILENAME" "$test_name" \
+      "$test_number"; then
+      status=1
+    fi
     let test_number+=1
   done
   exit "$status"
@@ -323,13 +327,14 @@ bats_perform_test() {
   BATS_TEST_NAME="$1"
   if declare -F "$BATS_TEST_NAME" >/dev/null; then
     BATS_TEST_NUMBER="$2"
-    if [ -z "$BATS_TEST_NUMBER" ]; then
-      echo "1..1"
-      BATS_TEST_NUMBER="1"
+    if [[ -z "$BATS_TEST_NUMBER" ]]; then
+      printf '1..1\n'
+      BATS_TEST_NUMBER=1
     fi
 
     BATS_TEST_COMPLETED=""
     BATS_TEARDOWN_COMPLETED=""
+    BATS_ERROR_STATUS=""
     trap "bats_debug_trap \"\$BASH_SOURCE\"" debug
     trap "bats_error_trap" err
     trap "bats_teardown_trap" exit
@@ -339,12 +344,12 @@ bats_perform_test() {
     bats_teardown_trap
 
   else
-    echo "bats: unknown test name \`$BATS_TEST_NAME'" >&2
+    printf "bats: unknown test name \`%s'\n" "$BATS_TEST_NAME" >&2
     exit 1
   fi
 }
 
-if [ -z "$TMPDIR" ]; then
+if [[ -z "$TMPDIR" ]]; then
   BATS_TMPDIR="/tmp"
 else
   BATS_TMPDIR="${TMPDIR%/}"
@@ -359,14 +364,41 @@ bats_preprocess_source() {
   . bats-preprocess <<< "$(< "$BATS_TEST_FILENAME")"$'\n' > "$BATS_TEST_SOURCE"
   trap "bats_cleanup_preprocessed_source" err exit
   trap "bats_cleanup_preprocessed_source; exit 1" int
+
+  bats_detect_duplicate_test_case_names
 }
 
 bats_cleanup_preprocessed_source() {
   rm -f "$BATS_TEST_SOURCE"
 }
 
+bats_detect_duplicate_test_case_names() {
+  local test_names=()
+  local test_dupes=()
+  local line
+
+  while read -r line; do
+    if [[ ! "$line" =~ ^bats_test_function\  ]]; then
+      continue
+    fi
+    line="${line%$'\r'}"
+    line="${line#* }"
+
+    if [[ " ${test_names[*]} " == *" $line "* ]]; then
+      test_dupes+=("$line")
+      continue
+    fi
+    test_names+=("$line")
+  done <"$BATS_TEST_SOURCE"
+
+  if [[ "${#test_dupes[@]}" -ne 0 ]]; then
+    printf 'bats warning: duplicate test name(s) in %s: %s\n' \
+      "$BATS_TEST_FILENAME" "${test_dupes[*]}" >&2
+  fi
+}
+
 bats_evaluate_preprocessed_source() {
-  if [ -z "$BATS_TEST_SOURCE" ]; then
+  if [[ -z "$BATS_TEST_SOURCE" ]]; then
     BATS_TEST_SOURCE="${BATS_PARENT_TMPNAME}.src"
   fi
   source "$BATS_TEST_SOURCE"
@@ -374,12 +406,12 @@ bats_evaluate_preprocessed_source() {
 
 exec 3<&1
 
-if [ "$#" -eq 0 ]; then
+if [[ "$#" -eq 0 ]]; then
   bats_preprocess_source
   bats_evaluate_preprocessed_source
 
-  if [ -n "$BATS_COUNT_ONLY" ]; then
-    echo "${#BATS_TEST_NAMES[@]}"
+  if [[ -n "$BATS_COUNT_ONLY" ]]; then
+    printf '%d\n' "${#BATS_TEST_NAMES[@]}"
   else
     bats_perform_tests "${BATS_TEST_NAMES[@]}"
   fi
